/**
 * Created on 2021/12/14.
 */
package tw.com.leadtek.nhiwidget.dao;

import java.util.List;
import java.util.Map;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;

import tw.com.leadtek.nhiwidget.model.rdb.DEDUCTED_NOTE;

public interface DEDUCTED_NOTEDao extends JpaRepository<DEDUCTED_NOTE, Long>, JpaSpecificationExecutor<DEDUCTED_NOTE> {

	public List<DEDUCTED_NOTE> findByMrIdOrderById(Long mrId);

	/**
	 * 取得核刪各類別點數、件數
	 * 
	 * @param sdate
	 * @param edate
	 * @return
	 */
	@Query(value = "SELECT * FROM  "
			+ "(SELECT COALESCE(SUM(DEDUCTED_AMOUNT),0) AS NOPROJCET_AMOUNT_OP  FROM DEDUCTED_NOTE, MR WHERE MR.ID =  DEDUCTED_NOTE.MR_ID AND DATA_FORMAT = '10' AND ITEM  = '非專案' AND DEDUCTED_DATE BETWEEN  ?1 AND  ?2)a, "
			+ "(SELECT COALESCE(SUM(DEDUCTED_AMOUNT),0) AS PROJCET_AMOUNT_OP  FROM DEDUCTED_NOTE, MR WHERE MR.ID =  DEDUCTED_NOTE.MR_ID AND DATA_FORMAT = '10' AND ITEM  = '專案' AND DEDUCTED_DATE BETWEEN  ?1 AND  ?2)b, "
			+ "(SELECT COALESCE(SUM(DEDUCTED_AMOUNT),0) AS MED_AMOUNT_OP  FROM DEDUCTED_NOTE, MR WHERE MR.ID =  DEDUCTED_NOTE.MR_ID AND DATA_FORMAT = '10' AND ITEM  = '藥費' AND DEDUCTED_DATE BETWEEN  ?1 AND  ?2)c, "
			+ "(SELECT COALESCE(SUM(DEDUCTED_AMOUNT),0) AS NOPROJCET_AMOUNT_IP  FROM DEDUCTED_NOTE, MR WHERE MR.ID =  DEDUCTED_NOTE.MR_ID AND DATA_FORMAT = '20' AND ITEM  = '非專案' AND DEDUCTED_DATE BETWEEN  ?1 AND  ?2)d, "
			+ "(SELECT COALESCE(SUM(DEDUCTED_AMOUNT),0) AS PROJCET_AMOUNT_IP  FROM DEDUCTED_NOTE, MR WHERE MR.ID =  DEDUCTED_NOTE.MR_ID AND DATA_FORMAT = '20' AND ITEM  = '專案' AND DEDUCTED_DATE BETWEEN  ?1 AND  ?2)e, "
			+ "(SELECT COALESCE(SUM(DEDUCTED_AMOUNT),0) AS MED_AMOUNT_IP  FROM DEDUCTED_NOTE, MR WHERE MR.ID =  DEDUCTED_NOTE.MR_ID AND DATA_FORMAT = '20' AND ITEM  = '藥費' AND DEDUCTED_DATE BETWEEN  ?1 AND  ?2)f, "
			+ "(SELECT COALESCE(SUM(DEDUCTED_QUANTITY),0) AS NOPROJCET_QUANTITY_OP  FROM DEDUCTED_NOTE, MR WHERE MR.ID =  DEDUCTED_NOTE.MR_ID AND DATA_FORMAT = '10' AND ITEM  = '非專案' AND DEDUCTED_DATE BETWEEN  ?1 AND  ?2)g, "
			+ "(SELECT COALESCE(SUM(DEDUCTED_QUANTITY),0) AS PROJCET_QUANTITY_OP  FROM DEDUCTED_NOTE, MR WHERE MR.ID =  DEDUCTED_NOTE.MR_ID AND DATA_FORMAT = '10' AND ITEM  = '專案' AND DEDUCTED_DATE BETWEEN  ?1 AND  ?2)h, "
			+ "(SELECT COALESCE(SUM(DEDUCTED_QUANTITY),0) AS MED_QUANTITY_OP  FROM DEDUCTED_NOTE, MR WHERE MR.ID =  DEDUCTED_NOTE.MR_ID AND DATA_FORMAT = '10' AND ITEM  = '藥費' AND DEDUCTED_DATE BETWEEN  ?1 AND  ?2)i, "
			+ "(SELECT COALESCE(SUM(DEDUCTED_QUANTITY),0) AS NOPROJCET_QUANTITY_IP  FROM DEDUCTED_NOTE, MR WHERE MR.ID =  DEDUCTED_NOTE.MR_ID AND DATA_FORMAT = '20' AND ITEM  = '非專案' AND DEDUCTED_DATE BETWEEN  ?1 AND  ?2)j, "
			+ "(SELECT COALESCE(SUM(DEDUCTED_QUANTITY),0) AS PROJCET_QUANTITY_IP  FROM DEDUCTED_NOTE, MR WHERE MR.ID =  DEDUCTED_NOTE.MR_ID AND DATA_FORMAT = '20' AND ITEM  = '專案' AND DEDUCTED_DATE BETWEEN  ?1 AND  ?2)k, "
			+ "(SELECT COALESCE(SUM(DEDUCTED_QUANTITY),0) AS MED_QUANTITY_IP  FROM DEDUCTED_NOTE, MR WHERE MR.ID =  DEDUCTED_NOTE.MR_ID AND DATA_FORMAT = '20' AND ITEM  = '藥費' AND DEDUCTED_DATE BETWEEN  ?1 AND  ?2)l, "
			+ "(SELECT COALESCE(SUM(DEDUCTED_QUANTITY),0) AS QUANTITY  FROM DEDUCTED_NOTE, MR WHERE MR.ID =  DEDUCTED_NOTE.MR_ID  AND DEDUCTED_DATE BETWEEN  ?1 AND  ?2)n, "
			+ "(SELECT COALESCE(SUM(CAST(VAL AS INT)),0) AS EXTRACTCASE  FROM PARAMETERS WHERE NOTE = '核刪抽件數' AND END_DATE BETWEEN  ?1 AND  ?2)m "
			+ "", nativeQuery = true)
	public Map<String, Object> getAmountDataByDate(String sdate, String edate);

	/**
	 * 取得核刪醫令點數資料
	 * 
	 * @param sdate
	 * @param edate
	 * @return
	 */
	@Query(value = "SELECT MR.DATA_FORMAT , CONCAT(CONCAT(DEDUCTED_ORDER,'-'), a.NAME) AS NAME,  SUM(DEDUCTED_AMOUNT) AMOUNT, REASON FROM DEDUCTED_NOTE,MR, "
			+ "(SELECT DISTINCT CODE, NAME FROM PAY_CODE WHERE CODE IN (SELECT DEDUCTED_ORDER FROM DEDUCTED_NOTE GROUP BY DEDUCTED_ORDER)) a  "
			+ "WHERE MR.ID = DEDUCTED_NOTE.MR_ID AND DEDUCTED_NOTE.DEDUCTED_ORDER = a.CODE AND DEDUCTED_DATE BETWEEN ?1 AND ?2 "
			+ "GROUP BY DEDUCTED_NOTE.DEDUCTED_ORDER, a.NAME, DEDUCTED_NOTE.REASON, MR.DATA_FORMAT  "
			+ "", nativeQuery = true)
	public List<Map<String, Object>> getDeductedOrderAmountByDate(String sdate, String edate);
	 /**
	  * 核刪醫令資料,放大回推
	  * @param sdate
	  * @param edate
	  * @return
	  */
	@Query(value = "SELECT MR.DATA_FORMAT , CONCAT(CONCAT(DEDUCTED_ORDER,'-'), a.NAME) AS NAME,  SUM(ROLLBACK_M) AS  AMOUNT, SUM(AFR_QUANTITY) AS AFR_QUANTITY, SUM(AFR_AMOUNT) AS AFR_AMOUNT, SUM(AFR_PAY_QUANTITY) AS AFR_PAY_QUANTITY, SUM(AFR_PAY_AMOUNT) AS AFR_PAY_AMOUNT  FROM DEDUCTED_NOTE,MR, "
			+ "(SELECT DISTINCT CODE, NAME FROM PAY_CODE WHERE CODE IN (SELECT DEDUCTED_ORDER FROM DEDUCTED_NOTE GROUP BY DEDUCTED_ORDER)) a  "
			+ "WHERE MR.ID = DEDUCTED_NOTE.MR_ID AND DEDUCTED_NOTE.DEDUCTED_ORDER = a.CODE AND ROLLBACK_DATE  BETWEEN ?1 AND ?2 "
			+ "GROUP BY DEDUCTED_NOTE.DEDUCTED_ORDER, a.NAME, MR.DATA_FORMAT  "
			+ "", nativeQuery = true)
	public List<Map<String,Object>> getRollbackOrderAmountByDate(String sdate, String edate);
	
	/**
	 * 核刪醫令資料,爭議
	 * @param sdate
	 * @param edate
	 * @return
	 */
	@Query(value = "SELECT MR.DATA_FORMAT , CONCAT(CONCAT(DEDUCTED_ORDER,'-'), a.NAME) AS NAME, SUM(DISPUTE_QUANTITY) AS DISPUTE_QUANTITY, SUM(DISPUTE_AMOUNT) AS DISPUTE_AMOUNT, SUM(DISPUTE_PAY_QUANTITY) AS DISPUTE_PAY_QUANTITY, SUM(DISPUTE_PAY_AMOUNT) AS DISPUTE_PAY_AMOUNT, DISPUTE_NO_PAY_CODE  FROM DEDUCTED_NOTE,MR, "
			+ "(SELECT DISTINCT CODE, NAME FROM PAY_CODE WHERE CODE IN (SELECT DEDUCTED_ORDER FROM DEDUCTED_NOTE GROUP BY DEDUCTED_ORDER)) a  "
			+ "WHERE MR.ID = DEDUCTED_NOTE.MR_ID AND DEDUCTED_NOTE.DEDUCTED_ORDER = a.CODE AND DISPUTE_DATE  BETWEEN ?1 AND ?2 "
			+ "GROUP BY DEDUCTED_NOTE.DEDUCTED_ORDER, a.NAME, MR.DATA_FORMAT, DEDUCTED_NOTE.DISPUTE_NO_PAY_CODE  "
			+ "", nativeQuery = true)
	public List<Map<String,Object>> getDisputeOrderAmountByDate(String sdate, String edate);

}
