# 59.120.139.60 -> ec2-54-168-152-76.ap-northeast-1.compute.amazonaws.com
server:
  port: ${port:8081}
  tomcat:
    uri-encoding: UTF-8
    max-connections: 3000
    max-http-form-post-size: 124857600
    threads:
      max: 1000
  max-http-header-size: 40KB
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true
  jackson:
    default-property-inclusion: NON_NULL
  redis:
    host: 59.120.139.62
#    host: 10.10.5.30
    port: 6379
    database: 0
    password: Leadtek
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 4
  datasource:
    url: jdbc:mariadb://${dbip:leadtek-aws-db.cdw1dvedcf5w.ap-northeast-1.rds.amazonaws.com}:${dbport:3306}/nwuser
    username: admin
    password: AWSLeadtek23850!
#  datasource:
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://${dbip:140.127.232.81}:${dbport:1433}; databaseName=ProjectData
#    username: sa
#    password: "!si7966"
#    connection-test-query: SELECT '1' FROM DUMMY
  jpa:
#    orm:
    mapping-resources: orm.xml
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        id: 
          new_generator_mappings: false
          connection:
          pool_size: 100
        format_sql: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
        temp:
          use_jdbc_metadata_defaults: false
      jdbc:
        batch_size: 1000
        lob:
          non_contextual_creation: true
      default-schema: nwuser
      connection:
        pool_size: 10
      show_sql: false
      format_sql: false
      bytecode: 
        provider: javassist
        use_reflection_optimizer: true
jwt:
  secret: leadtek_NHIWidget
# jwt expire time: 8 hours
  expiration: 28800000
# away from keyboard 時間，超過30分則刪除 jwt
  afk: 1800000
mail:
  host: 59.120.139.196
  port: 25
  fromEmail: monitor@leadtek.com.tw
  password: z5z8tah5
swagger:
  enable: true
  application-name: 健保申保最佳化系統 API
  application-version: 2.0
  application-description: 健保申保最佳化系統 API
  try-host: http://localhost:${server.port}