spring:
  profiles:
    active: leadtek-office-hana
#    active: localhost
#    active: leadtek-aws-maria
#    active: ms
#    active: pohai
#    active: sql-server
#    active: linyuan
#    active: 806
#    active: package