server:
  port: ${port:8080}
  tomcat:
    uri-encoding: UTF-8
    max-connections: 3000
    max-http-post-size: 124857600
    max-threads: 1000
  max-http-header-size: 124857600
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
spring:
  data:
    mongodb:
      host: 10.10.5.22
      port: 27017
      database: nhiwidget
      username: leadtek
      password: leadtek2020
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  redis:
    host: 10.10.5.30
    port: 6379
    database: 0
    password: Leadtek
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 4
        min-wait: 1
#  datasource:
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://${dbip:140.127.232.81}:${dbport:1433}; databaseName=ProjectData
#    username: sa
#    password: "!si7966"
#    connection-test-query: SELECT '1' FROM DUMMY
jwt:
  secret: leadtek_NHIWidget
  expiration: 360000000