server:
  port: ${port:8081}
  tomcat:
    uri-encoding: UTF-8
    max-connections: 3000
    max-http-post-size: 124857600
    max-threads: 1000
  max-http-header-size: 124857600
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
spring:
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true
#  jackson:
#    default-property-inclusion: non_null
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  redis:
    host: 10.10.5.30
    port: 6379
    database: 0
    password: Leadtek
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 4
        min-wait: 1
#  datasource:
#    hikari:
#      data-source-class-name: com.zaxxer.hikari.HikariDataSource
#      driver-class-name: com.sap.db.jdbc.Driver
#      url: 
#      username: NWUSER
#      password: Leadtek21191
#      connection-test-query: SELECT '1' FROM DUMMY
  datasource:
    url: jdbc:sap://10.10.5.55:30041/NHIWIDGET
    username: NWUSER
    password: Leadtek2021
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
#       dialect: org.hibernate.dialect.SAPDBDialect
       dialect: org.hibernate.dialect.HANAColumnStoreDialect
       id: 
        new_generator_mappings: false
        connection:
          pool_size: 10
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
        temp:
          use_jdbc_metadata_defaults: false
      jdbc:
        batch_size: 1000
        lob:
          non_contextual_creation: true
      default-schema: NHIWIDGET
      connection:
        pool_size: 5
      show_sql: false
      format_sql: true
      bytecode: 
        provider: javassist
        use_reflection_optimizer: true
#  datasource:
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://${dbip:140.127.232.81}:${dbport:1433}; databaseName=ProjectData
#    username: sa
#    password: "!si7966"
#    connection-test-query: SELECT '1' FROM DUMMY
springfox:
  documentation:
    swagger:
      use-model-v3: false
jwt:
  secret: leadtek_NHIWidget
  expiration: 360000000
mail:
  host: 59.120.139.196
  port: 25
  fromEmail: monitor@leadtek.com.tw
  password: z5z8tah5
swagger:
  enable: true
  application-name: 健保申保最佳化系統 API
  application-version: 2.0
  application-description: 健保申保最佳化系統 API
  try-host: http://localhost:${server.port}